<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>1.1.0</Version>
		<AssemblyVersion>1.1.0.0</AssemblyVersion>
		<FileVersion>1.1.0.0</FileVersion>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
	  <Optimize>True</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="BuildTools\**\*.cs" />
		<EmbeddedResource Remove="BuildTools\**\*" />
		<None Remove="BuildTools\**\*" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="ffmpeg.exe" />
		<None Remove="ffprobe.exe" />
		<None Remove="init.lua" />
		<None Remove="radvideo64.exe" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="ffmpeg.exe" />
		<EmbeddedResource Include="ffprobe.exe" />
		<EmbeddedResource Include="init.lua" />
		<EmbeddedResource Include="radvideo64.exe" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Downloads\WolvenKit-main\WolvenKit-main\WolvenKit.Common\WolvenKit.Common.csproj" />
		<ProjectReference Include="..\..\Downloads\WolvenKit-main\WolvenKit-main\WolvenKit.Core\WolvenKit.Core.csproj" />
		<ProjectReference Include="..\..\Downloads\WolvenKit-main\WolvenKit-main\WolvenKit.RED4\WolvenKit.RED4.csproj" />
	</ItemGroup>

</Project>
